//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gproject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gproject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridėti.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresas.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniVet registracija.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppJoinDGV.
        /// </summary>
        internal static string appointmentJoinDGV {
            get {
                return ResourceManager.GetString("appointmentJoinDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Susitikimai.
        /// </summary>
        internal static string appointments {
            get {
                return ResourceManager.GetString("appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Susitikimai pasirinktam klientui.
        /// </summary>
        internal static string appointmentsForSelectedClient {
            get {
                return ResourceManager.GetString("appointmentsForSelectedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Susitikimai pasirinktam augintiniui.
        /// </summary>
        internal static string appointmentsForSelectedPet {
            get {
                return ResourceManager.GetString("appointmentsForSelectedPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atvyko.
        /// </summary>
        internal static string arrived {
            get {
                return ResourceManager.GetString("arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutraukti.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atšaukta.
        /// </summary>
        internal static string canceled {
            get {
                return ResourceManager.GetString("canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string checkIfDataFieldContainsDate {
            get {
                return ResourceManager.GetString("checkIfDataFieldContainsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientDGV.
        /// </summary>
        internal static string clientDGV {
            get {
                return ResourceManager.GetString("clientDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klientai.
        /// </summary>
        internal static string clients {
            get {
                return ResourceManager.GetString("clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentaras.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukurti.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridėti naują susitikimą.
        /// </summary>
        internal static string createAppointment {
            get {
                return ResourceManager.GetString("createAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridėti naują klientą.
        /// </summary>
        internal static string createClient {
            get {
                return ResourceManager.GetString("createClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klientas nerastas.
        /// </summary>
        internal static string createClientResultCaption {
            get {
                return ResourceManager.GetString("createClientResultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toks klientas nerastas. Ar norite sukurti naują klientą? .
        /// </summary>
        internal static string createClientResultForReal {
            get {
                return ResourceManager.GetString("createClientResultForReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridėti naują augintinį.
        /// </summary>
        internal static string createPet {
            get {
                return ResourceManager.GetString("createPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridėti naują darbuotoją.
        /// </summary>
        internal static string createStaff {
            get {
                return ResourceManager.GetString("createStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppointmentDate.
        /// </summary>
        internal static string dataBaseFieldAppointmentDate {
            get {
                return ResourceManager.GetString("dataBaseFieldAppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientAddress.
        /// </summary>
        internal static string dataBaseFieldClientAddress {
            get {
                return ResourceManager.GetString("dataBaseFieldClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientEmail.
        /// </summary>
        internal static string dataBaseFieldClientEmail {
            get {
                return ResourceManager.GetString("dataBaseFieldClientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientID.
        /// </summary>
        internal static string dataBaseFieldClientID {
            get {
                return ResourceManager.GetString("dataBaseFieldClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientName.
        /// </summary>
        internal static string dataBaseFieldClientName {
            get {
                return ResourceManager.GetString("dataBaseFieldClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientPhone1.
        /// </summary>
        internal static string dataBaseFieldClientPhone1 {
            get {
                return ResourceManager.GetString("dataBaseFieldClientPhone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientPhone2.
        /// </summary>
        internal static string dataBaseFieldClientPhone2 {
            get {
                return ResourceManager.GetString("dataBaseFieldClientPhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientRegDate.
        /// </summary>
        internal static string dataBaseFieldClientRegDate {
            get {
                return ResourceManager.GetString("dataBaseFieldClientRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientSurname.
        /// </summary>
        internal static string dataBaseFieldClientSurname {
            get {
                return ResourceManager.GetString("dataBaseFieldClientSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string dataBaseFieldComments {
            get {
                return ResourceManager.GetString("dataBaseFieldComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string dataBaseFieldID {
            get {
                return ResourceManager.GetString("dataBaseFieldID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PetBirthDate.
        /// </summary>
        internal static string dataBaseFieldPetBirthDate {
            get {
                return ResourceManager.GetString("dataBaseFieldPetBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PetGender.
        /// </summary>
        internal static string dataBaseFieldPetGender {
            get {
                return ResourceManager.GetString("dataBaseFieldPetGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PetName.
        /// </summary>
        internal static string dataBaseFieldPetName {
            get {
                return ResourceManager.GetString("dataBaseFieldPetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PetSpecies.
        /// </summary>
        internal static string dataBaseFieldPetSpecies {
            get {
                return ResourceManager.GetString("dataBaseFieldPetSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffAddress.
        /// </summary>
        internal static string dataBaseFieldStaffAddress {
            get {
                return ResourceManager.GetString("dataBaseFieldStaffAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffEmail.
        /// </summary>
        internal static string dataBaseFieldStaffEmail {
            get {
                return ResourceManager.GetString("dataBaseFieldStaffEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffName.
        /// </summary>
        internal static string dataBaseFieldStaffName {
            get {
                return ResourceManager.GetString("dataBaseFieldStaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffPhone1.
        /// </summary>
        internal static string dataBaseFieldStaffPhone1 {
            get {
                return ResourceManager.GetString("dataBaseFieldStaffPhone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffPhone2.
        /// </summary>
        internal static string dataBaseFieldStaffPhone2 {
            get {
                return ResourceManager.GetString("dataBaseFieldStaffPhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffQualification.
        /// </summary>
        internal static string dataBaseFieldStaffQualification {
            get {
                return ResourceManager.GetString("dataBaseFieldStaffQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffSurname.
        /// </summary>
        internal static string dataBaseFieldStaffSurname {
            get {
                return ResourceManager.GetString("dataBaseFieldStaffSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string dataBaseFieldStatus {
            get {
                return ResourceManager.GetString("dataBaseFieldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pašalinti.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinimas.
        /// </summary>
        internal static string deleteEntryCaption {
            get {
                return ResourceManager.GetString("deleteEntryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar tikrai ištrinti pasirinktą įrašą?.
        /// </summary>
        internal static string deleteEntryForReal {
            get {
                return ResourceManager.GetString("deleteEntryForReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gydytojas.
        /// </summary>
        internal static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyd. vardas.
        /// </summary>
        internal static string doctorName {
            get {
                return ResourceManager.GetString("doctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyd. pavardė.
        /// </summary>
        internal static string doctorSurname {
            get {
                return ResourceManager.GetString("doctorSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit50 {
            get {
                object obj = ResourceManager.GetObject("edit50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koreguoti.
        /// </summary>
        internal static string editBtn {
            get {
                return ResourceManager.GetString("editBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. paštas.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darbuotojo duomenų automatinio užpildymo metu įvyko klaida.
        /// </summary>
        internal static string erorMsgGetAutoCmpltStaffData {
            get {
                return ResourceManager.GetString("erorMsgGetAutoCmpltStaffData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Susitikimo duomenų gavimo metu įvyko klaida.
        /// </summary>
        internal static string errorMsgAppointmentData {
            get {
                return ResourceManager.GetString("errorMsgAppointmentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pašalinimo metu įvyko klaida.
        /// </summary>
        internal static string errorMsgDeleteFailed {
            get {
                return ResourceManager.GetString("errorMsgDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtravimo metu įvyko klaida.
        /// </summary>
        internal static string errorMsgFilteringFailed {
            get {
                return ResourceManager.GetString("errorMsgFilteringFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliento duomenų automatinio užpildymo metu įvyko klaida.
        /// </summary>
        internal static string errorMsgGetAutoCmpltClientData {
            get {
                return ResourceManager.GetString("errorMsgGetAutoCmpltClientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyvūno duomenų automatinio užpildymo metu įvyko klaida.
        /// </summary>
        internal static string errorMsgGetAutoCmpltPetData {
            get {
                return ResourceManager.GetString("errorMsgGetAutoCmpltPetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klientų duomenų gavimo metu įvyko klaida.
        /// </summary>
        internal static string errorMsgGettingClientID {
            get {
                return ResourceManager.GetString("errorMsgGettingClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darbuotojų duomenų gavimo metu įvyko klaida.
        /// </summary>
        internal static string errorMsgGettingStaffID {
            get {
                return ResourceManager.GetString("errorMsgGettingStaffID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridėjimo metu įvyko klaida.
        /// </summary>
        internal static string errorMsgInsertFailed {
            get {
                return ResourceManager.GetString("errorMsgInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyvūno duomenų gavimo metu įvyko klaida.
        /// </summary>
        internal static string errorMsgPetData {
            get {
                return ResourceManager.GetString("errorMsgPetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atnaujinimo metu įvyko klaida.
        /// </summary>
        internal static string errorMsgUpdateFailed {
            get {
                return ResourceManager.GetString("errorMsgUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filterTxtBox.
        /// </summary>
        internal static string filterTxtBox {
            get {
                return ResourceManager.GetString("filterTxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patelė.
        /// </summary>
        internal static string genderFemale {
            get {
                return ResourceManager.GetString("genderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patinas.
        /// </summary>
        internal static string genderMale {
            get {
                return ResourceManager.GetString("genderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vardas.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neatvyko.
        /// </summary>
        internal static string notArrived {
            get {
                return ResourceManager.GetString("notArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savininko adresas.
        /// </summary>
        internal static string ownerAddress {
            get {
                return ResourceManager.GetString("ownerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savininko vardas.
        /// </summary>
        internal static string ownerName {
            get {
                return ResourceManager.GetString("ownerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savininko pavardė.
        /// </summary>
        internal static string ownerSurname {
            get {
                return ResourceManager.GetString("ownerSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyvūno gimimo data.
        /// </summary>
        internal static string petBirthDate {
            get {
                return ResourceManager.GetString("petBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PetDGV.
        /// </summary>
        internal static string petDGV {
            get {
                return ResourceManager.GetString("petDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyvūno lytis.
        /// </summary>
        internal static string petGender {
            get {
                return ResourceManager.GetString("petGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyvūno vardas.
        /// </summary>
        internal static string petName {
            get {
                return ResourceManager.GetString("petName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augintiniai.
        /// </summary>
        internal static string pets {
            get {
                return ResourceManager.GetString("pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyvūno rūšis.
        /// </summary>
        internal static string petSpecies {
            get {
                return ResourceManager.GetString("petSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel. numeris.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peržiūrėti klientą.
        /// </summary>
        internal static string previewClient {
            get {
                return ResourceManager.GetString("previewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peržiūrėti augintinį.
        /// </summary>
        internal static string previewPet {
            get {
                return ResourceManager.GetString("previewPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvalifikacija.
        /// </summary>
        internal static string qualification {
            get {
                return ResourceManager.GetString("qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registravimo data.
        /// </summary>
        internal static string regDate {
            get {
                return ResourceManager.GetString("regDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darbuotojai.
        /// </summary>
        internal static string staff {
            get {
                return ResourceManager.GetString("staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffDGV.
        /// </summary>
        internal static string staffDGV {
            get {
                return ResourceManager.GetString("staffDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusas.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pavardė.
        /// </summary>
        internal static string surName {
            get {
                return ResourceManager.GetString("surName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laikas.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodyti tik šios dienos įrašus.
        /// </summary>
        internal static string todayEntries {
            get {
                return ResourceManager.GetString("todayEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koreguoti susitikimą.
        /// </summary>
        internal static string updateAppointment {
            get {
                return ResourceManager.GetString("updateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koreguoti klientą.
        /// </summary>
        internal static string updateClient {
            get {
                return ResourceManager.GetString("updateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koreguoti augintinį.
        /// </summary>
        internal static string updatePet {
            get {
                return ResourceManager.GetString("updatePet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koreguoti darbuotoją.
        /// </summary>
        internal static string updateStaff {
            get {
                return ResourceManager.GetString("updateStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view50 {
            get {
                object obj = ResourceManager.GetObject("view50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peržiūrėti.
        /// </summary>
        internal static string viewBtn {
            get {
                return ResourceManager.GetString("viewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laukiama.
        /// </summary>
        internal static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
    }
}
